# Generated by Django 2.1.5 on 2019-01-10 12:02
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import migrations
from sports_betting.models import Team



def load_teams(apps, schema_editor):
    #East
    Team.objects.create(name='Heat', city='Miami', conference='E')
    Team.objects.create(name='Celtics', city='Boston', conference='E')
    Team.objects.create(name='Nets', city='Brooklyn', conference='E')
    Team.objects.create(name='Hornets', city='Charlotte', conference='E')
    Team.objects.create(name='Magic', city='Orlando', conference='E')
    Team.objects.create(name='Raptors', city='Toronto', conference='E')
    Team.objects.create(name='Knicks', city='New York', conference='E')
    Team.objects.create(name='76ers', city='Philadelphia', conference='E')
    Team.objects.create(name='Bulls', city='Chicago', conference='E')
    Team.objects.create(name='Pistons', city='Detroit', conference='E')
    Team.objects.create(name='Pacers', city='Indiana', conference='E')
    Team.objects.create(name='Bucks', city='Milwaukee', conference='E')
    Team.objects.create(name='Hawks', city='Atlanta', conference='E')
    Team.objects.create(name='Wizards', city='Washington', conference='E')
    Team.objects.create(name='Cavaliers', city='Cleveland', conference='E')
    #West
    Team.objects.create(name='Warriors', city='Golden State', conference='W')
    Team.objects.create(name='Lakers', city='Los Angeles', conference='W')
    Team.objects.create(name='Clippers', city='Los Angeles', conference='W')
    Team.objects.create(name='Suns', city='Phoenix', conference='W')
    Team.objects.create(name='Kings', city='Sacramento', conference='W')
    Team.objects.create(name='Jazz', city='Utah', conference='W')
    Team.objects.create(name='Timberwolves', city='Minnesota', conference='W')
    Team.objects.create(name='Thunder', city='Oklahoma City', conference='W')
    Team.objects.create(name='Trail Blazers', city='Portland', conference='W')
    Team.objects.create(name='Nuggets', city='Denver', conference='W')
    Team.objects.create(name='Mavericks', city='Dallas', conference='W')
    Team.objects.create(name='Rockets', city='Houston', conference='W')
    Team.objects.create(name='Grizzlies', city='Memphis', conference='W')
    Team.objects.create(name='Pelicans', city='New Orleans', conference='W')
    Team.objects.create(name='Spurs', city='San Antonio', conference='W')



def delete_teams(apps, schema_editor):
    Team.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('sports_betting', '0001_initial'),  #zmienic to bo ta migracja ma byc po poczatkowej
    ]

    operations = [
        migrations.RunPython(load_teams, delete_teams),
    ]
